name = "holopak"
author = "kukin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1179f09b3ec5fa5f5d0cb02830c1fa757df0c80e58e312c0fbfb7066fc230c25"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
