#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jul 01 07:52:25 EDT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=19
shaderPack=ComplementaryReimagined_r5.5.1.zip
