name = "holoworld"
author = "kukin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9748b75d8ad0f0273f2d9db67ba8ec217e41257f390916f76e9c440354dbebc9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
