name = "holoworld"
author = "kukin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4588b12abd718efaf7a21dd9256695d019d679c1ec8c683221193a205184089f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
