name = "holoworld"
author = "kukin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e4e3d8f3036edbe7a586745183ba0270561240646d752e1da354e53538bc13c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
